# Generated by Django 4.2.5 on 2023-09-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('rodzaj', models.IntegerField(choices=[(1, 'Miasto'), (2, 'Mafia')])),
                ('priorytet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gracz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('numer', models.IntegerField()),
                ('idGra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.gra')),
                ('idRola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.rola')),
            ],
        ),
    ]
