# Generated by Django 4.2.4 on 2023-09-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0003_alter_gra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gracz',
            name='glosy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Runda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('idGra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.gra')),
            ],
        ),
        migrations.CreateModel(
            name='Ruch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('idGracz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.gracz')),
                ('idRola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.rola')),
                ('idRunda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.runda')),
            ],
        ),
    ]
